doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        driver: 'pdo_pgsql'
        charset: utf8
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'

        # https://www.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/working-with-datetime.html
        types:
            utcdatetime:
                name: datetime
                class: App\DoctrineExtensions\DBAL\Types\UTCDateTimeType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
