# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        # https://symfony.com/doc/2.0/bundles/LiipImagineBundle/cache-resolver/aws_s3.html
        s3_cache:
            aws_s3:
                client_config:
                    credentials:
                        key:    '%env(AWS_S3_KEY)%'
                        secret: '%env(AWS_S3_SECRET)%'
                    region: '%env(AWS_S3_REGION)%'
                    version: 'latest'
                    # https://github.com/aws/aws-sdk-php/issues/692#issuecomment-121731538
                    endpoint: 'https://%env(AWS_S3_ENDPOINT)%'
                    bucket_endpoint: true
                bucket: '%env(AWS_S3_BUCKET)%'
                get_options:
                    Scheme: https
                put_options:
                    CacheControl: "max-age=86400"

        default:
            web_path:
                cache_prefix: "/"


    filter_sets:
        cache: ~

        # Strip EXIF information
        img:
            cache: s3_cache
            filters:
                strip: ~

        # the name of the "filter set"
        thumb:
            cache: s3_cache
            quality: 75
            png_compression_level: 8

            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x120 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [120, 120], mode: outbound }

                # auto rotate the image using EXIF metadata
                auto_rotate: ~

    # https://symfony.com/doc/2.0/bundles/LiipImagineBundle/data-loader/flysystem.html
    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.default_filesystem_filesystem

    data_loader: flysystem_loader