# See docs how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    enqueue: true

    # cache: s3_cache
    cache: default

    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    resolvers:
        s3_cache:
            flysystem:
                filesystem_service: oneup_flysystem.s3_filesystem
                root_url:           '%env(S3_ROOTURL)%'
                cache_prefix:       "/"
                visibility:         public

        default:
            web_path:
                cache_prefix: "/"


    filter_sets:
        img:
            # cache: s3_cache
            cache: default
            animated: true
            filters:
                strip: ~

        # the name of the "filter set"
        thumb:
            # cache: s3_cache
            cache: default
            quality: 75
            png_compression_level: 8
            animated: true

            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x120 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [120, 120], mode: outbound }

                # auto rotate the image using EXIF metadata
                auto_rotate: ~
            # post_processors:
            #     mozjpeg: { quality: 70 }

    # https://symfony.com/doc/2.0/bundles/LiipImagineBundle/data-loader/flysystem.html
    loaders:
        flysystem_loader:
            flysystem:
                # filesystem_service: oneup_flysystem.s3_filesystem
                filesystem_service: oneup_flysystem.local_filesystem
                

    data_loader: flysystem_loader