# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
# https://symfony.com/doc/2.0/bundles/LiipImagineBundle/data-loader/flysystem.html
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: '%kernel.project_dir%/var/storage/default'

        acme.flysystem_adapter:
            awss3v3:
                client: acme.s3_client
                bucket: '%env(AWS_S3_BUCKET)%'
                prefix: ~
        
    filesystems:
        default_filesystem:
            adapter: acme.flysystem_adapter
            alias: League\Flysystem\Filesystem
            mount: default_filesystem
