# https://github.com/dustin10/VichUploaderBundle/blob/master/docs/storage/flysystem.md
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        post_image:
            upload_destination: s3_filesystem
            namer:
                service: Vich\UploaderBundle\Naming\Base64Namer
                options: { length: '6'}
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

            uri_prefix: 'https://%env(AWS_S3_ENDPOINT)%'