vich_uploader:
    db_driver: orm

    mappings:
        post_image:
            uri_prefix: /images/posts
            upload_destination: '%kernel.project_dir%/public/images/posts'
            namer:
                service: Vich\UploaderBundle\Naming\Base64Namer
                options: { length: '6'}
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true