version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php-fpm:
    container_name: web-2kanna-php
    build:
      context: ./php-fpm
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ../:/var/www

  nginx:
    container_name: web-2kanna-nginx
    build:
      context: ./nginx
    environment:
      - VIRTUAL_HOST={$VIRTUAL_HOST}
      - LETSENCRYPT_HOST={$VIRTUAL_HOST}
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    # If you want to expose port 80 to the host
    # ports:
    #   - "80:80"

networks:
  default:
    name: web
