name: CI

on: [push]


jobs:
  build-test:
    runs-on: ubuntu-latest
    

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: imagick
  
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1
      
    - uses: php-actions/phpunit@v1
      with:
        config: ./phpunit.xml.dist
        memory: 256M
    
